function MRP_rawData = importFile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  MONKEYDATA = IMPORTFILE(FILENAME) reads data from text file FILENAME
%  for the default selection.  Returns the data as a table.
%
%  MONKEYDATA = IMPORTFILE(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  MonkeyData = importfile("/Users/rgal0005/Dropbox/Research/tLab/Programming/Inquisit_Matlab_workFlow/Gallagher2020_data/Monkey_Data.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 04-May-2020 14:51:27

disp('getting raw data... '); pause(2);
%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 37);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["subject", "blockcode", "trialcode", "Var4", "latency", "response", "imageName", "Var8", "Var9", "Var10", "Var11", "Var12", "Var13", "Var14", "Var15", "Var16", "Var17", "Var18", "Var19", "Var20", "Var21", "Var22", "Var23", "Var24", "Var25", "Var26", "Var27", "Var28", "Var29", "Var30", "Var31", "wordNumber", "Var33", "imageNumber", "Var35", "word", "Var37"];
opts.SelectedVariableNames = ["subject", "blockcode", "trialcode", "latency", "response", "imageName", "wordNumber", "imageNumber", "word"];
opts.VariableTypes = ["string", "categorical", "categorical", "string", "double", "categorical", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "categorical", "string", "categorical", "string", "string", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["subject", "Var4", "imageName", "Var8", "Var9", "Var10", "Var11", "Var12", "Var13", "Var14", "Var15", "Var16", "Var17", "Var18", "Var19", "Var20", "Var21", "Var22", "Var23", "Var24", "Var25", "Var26", "Var27", "Var28", "Var29", "Var30", "Var31", "Var33", "Var35", "word", "Var37"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["subject", "blockcode", "trialcode", "Var4", "response", "imageName", "Var8", "Var9", "Var10", "Var11", "Var12", "Var13", "Var14", "Var15", "Var16", "Var17", "Var18", "Var19", "Var20", "Var21", "Var22", "Var23", "Var24", "Var25", "Var26", "Var27", "Var28", "Var29", "Var30", "Var31", "wordNumber", "Var33", "imageNumber", "Var35", "word", "Var37"], "EmptyFieldRule", "auto");

% Import the data
MRP_rawData = readtable(filename, opts);

end

