function visualise_exclusionCriteria(X1, Y1)
%CREATEFIGURE(X1, Y1)
%  X1:  scatter x
%  Y1:  scatter y

%  Auto-generated by MATLAB on 12-May-2020 09:55:16

% Create figure
figure1 = figure('Color',[1 1 1]);

% Create axes
axes1 = axes('Parent',figure1,...
    'Position',[0.411666666666667 0.11 0.211666666666667 0.815]);
hold(axes1,'on');

% Create scatter
scatter(X1,Y1);

% Create ylabel
ylabel('Participant','FontSize',16);

% Create xlabel
xlabel('Catch Accuracy');

hold(axes1,'off');
% Set the remaining axes properties
set(axes1,'FontSize',12,'XTick',[0 0.25 0.5 0.75 1],'YTick',...
    [0 2 4 6 8 10 12 14 16 18],'YTickLabel',{'','','','','','','','','',''});
